INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('raising_adelina', 'Imagine Adelina is crying and you can''t immediately figure out why. Which response is most likely to help her calm down?', '["A) Say ''You''re okay, you''re okay'' in an upbeat voice to reassure her","B) Get close, make eye contact, and say something like ''I hear you, I''m right here'' — even if you don''t know why she''s upset yet","C) Give her a few minutes alone to settle herself down","D) Distract her with a toy or a funny face to redirect her attention"]', 'B) Get close, make eye contact, and say something like ''I hear you, I''m right here'' — even if you don''t know why she''s upset yet', 'multiple_choice', 'Options A and D are the typical reactions when a baby is crying. However, they skip the baby''s experience, which causes her nervous system to register a mismatch. What actually calms a baby''s stress response (measured in brain scans) is the feeling of being *seen* — a familiar face, a calm voice, the sense that someone is *with* her in the experience. She doesn''t need the problem solved immediately. She needs to know she''s not alone.', 'crying, soothing', 1, 0);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('raising_adelina', 'In 1975, researchers at the University of Minnesota began following a group of babies all the way into adulthood — tracking their friendships, mental health, confidence, and ability to handle life''s hard moments decades later.

What turned out to be the single biggest predictor of how well those kids did as adults?

Note: This factor mattered more than how smart they were, and more than how much money their family had.', '["A) How intelligent they were","B) Whether their family had financial stability","C) How reliably and warmly their caregivers responded to them as babies","D) Whether they had siblings"]', 'C) How reliably and warmly their caregivers responded to them as babies', 'multiple_choice', 'Led by Dr. Alan Sroufe, this study — one of the longest of its kind ever conducted — followed the same people from birth through their 30s. The factor that predicted healthy adult relationships, emotional resilience, and overall wellbeing above almost anything else was simple: did a trusted adult show up for them, consistently and warmly, when they were babies?

Not perfectly. Not with any special technique. Just: reliably there.

Wealth mattered less. IQ mattered less. Every time you respond to Adelina — every time you pick her up, look her in the eyes, or say ''I''ve got you'' — you are making a deposit into something that will pay off for the rest of her life.', 'attachment, development', 1, 0);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('raising_adelina', 'True or False: The faster and more consistently you respond to Adelina''s crying now, the more clingy and dependent she will be as a toddler.', '["True","False"]', 'False — and the research points the other direction entirely', 'true_false', 'This is one of the most common and understandable worries grandparents have — and one of the most thoroughly disproven by research. Researchers Bell and Ainsworth tracked babies in 1972 (with the study replicated many times since) and found that babies whose cries were answered promptly and consistently in their first year actually cried *less* by the end of that year — not more. And at ages 1, 2, and 3, they showed *greater* independence than babies whose cries went unanswered.

Here''s the intuition behind it: a baby who learns that the world responds to her doesn''t need to escalate to be heard. She''s been shown, over and over, that help comes. That trust is what eventually lets her venture out on her own — because she knows someone is there if she needs them.

You cannot spoil Adelina by showing up for her. What you''re actually building is confidence.', 'attachment, crying, development', 1, 0);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('raising_adelina', 'When Adelina is upset and crying, which of these phrases is most likely to actually calm her down — according to brain research?

(Pick the one that feels most natural to say.)', '["A) ''Shhh, shhh, it''s okay, stop crying''","B) ''Oh look — look at this! Look at the doggie!''","C) ''You''re really upset right now. I''m right here with you.''","D) ''There''s nothing to cry about, you''re fine''"]', 'C) ''You''re really upset right now. I''m right here with you.''', 'multiple_choice', 'UCLA neuroscientist Dr. Matthew Lieberman used brain imaging to study what happens when you put a name to a feeling out loud — and found that it literally reduces activity in the amygdala, the brain''s alarm center. Less alarm, less distress, more calm.

Dr. Daniel Siegel, a Harvard-trained psychiatrist, calls this ''name it to tame it.''

Here''s the important part for Adelina specifically: she doesn''t need to understand the words yet for this to work. What her nervous system picks up is your tone, your pace, your calm — and the fact that you''re *with* her rather than trying to rush her through the feeling. That signal — ''you''re not alone in this'' — is what actually turns the alarm down.

Saying ''you''re fine'' when she''s clearly not sends a small mixed message her body notices, even when her brain can''t name it. ''I see that you''re upset'' honors what''s real — and that''s what helps.', 'crying, soothing, talking', 1, 0);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('raising_adelina', 'True or False: When Adelina cries at 5 months old, she might just be doing it for attention — trying to get someone to pick her up.', '["True","False"]', 'False — a 5-month-old cannot cry ''just for attention'' the way an older child might', 'true_false', 'This one surprises a lot of people — because it feels so intuitive that babies ''learn'' to cry for attention. And they do, eventually. But not at 5 months.

At this age, a baby''s brain doesn''t yet have the wiring to think: ''If I cry, they''ll come.'' That kind of cause-and-effect reasoning develops much later. At 5 months, crying is purely instinctual. It always means something: hunger, discomfort, overstimulation, tiredness, or the need to feel close to someone.

There is no such thing as a manipulative 5-month-old. When Adelina cries, she is communicating. Every time you respond, you are teaching her two things at once: the world is safe, and *you* are someone she can count on.', 'crying, development, holding', 1, 0);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('raising_adelina', 'Picture this: You and Adelina are having a great moment — she''s looking right at you, cooing, totally locked in. Then your phone buzzes and you glance down, going quiet and still for about 30 seconds.

What does research suggest Adelina will do?', '["A) She''ll move on and entertain herself — babies are adaptable","B) She''ll notice almost immediately and try hard to get your attention back — and may get visibly distressed if she can''t","C) She won''t notice for at least a few minutes","D) She''ll use the quiet time to look around and explore on her own"]', 'B) She''ll notice almost immediately and try hard to get your attention back — and may get visibly distressed if she can''t', 'multiple_choice', 'This is based on one of the most famous experiments in infant psychology, called the Still Face Experiment, designed by Dr. Ed Tronick in 1975 and replicated hundreds of times since.

In the experiment, a mother playing warmly with her baby was instructed to suddenly go still and expressionless — like someone staring at a phone. Within seconds, babies as young as 2 months tried everything to bring her back: bigger smiles, pointing, vocalizing. When she didn''t respond, they became distressed — turning away, slumping, crying.

The other finding that surprised researchers: even after the mother re-engaged warmly, it took a little while for the baby to recover and trust the connection again.

This isn''t about phones being bad. It''s a window into how intensely tuned in to *you* Adelina already is. Your face, your attention, your presence — these are her whole world right now. And that is actually a beautiful thing.', 'attachment, development, playing, smiling', 1, 0);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('raising_adelina', 'When Adelina is having a really hard time — inconsolable, really worked up — what does she need most from you in that moment?', '["A) Quiet and space — overstimulation may be the problem","B) Your calm. She literally borrows your steadiness to help settle her own nervous system.","C) Something new to focus on — a change of scenery","D) To be put down so she learns to soothe herself"]', 'B) Your calm. She literally borrows your steadiness to help settle her own nervous system.', 'multiple_choice', 'Babies are born without the neurological wiring to calm themselves down — that part of the brain isn''t developed yet and won''t be for years. In the meantime, they do something remarkable: they *borrow* regulation from the adults around them.

This is called co-regulation, and it works like this: your nervous system and hers are in constant quiet communication. When you hold her with a steady, unhurried calm — slow breathing, a low soft voice, a firm gentle hold — her stress hormones actually begin to decrease in response to yours. Your body is talking to her body.

The flip side is also true: if you tense up when she cries, she feels that and it can make things worse.

You don''t have to fix it immediately. You don''t have to have the answer. You just have to be *calm with her in it.* That is the most powerful thing you can offer — and it works.', 'crying, holding, soothing', 1, 0);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('raising_adelina', 'True or False: Holding Adelina a lot, cuddling her when she cries, and keeping her close will make her too dependent and slow down her development of independence.', '["True","False"]', 'False — consistent closeness in infancy actually predicts more independence later, not less', 'true_false', 'The instinct behind this worry is completely understandable — it feels logical that more holding creates more need for holding. But the research consistently shows the opposite.

Think of it like a gas tank. A baby whose need for closeness is consistently filled develops an internal sense that the world is safe and that help is available if she needs it. From that foundation, she''s more willing to venture out, try new things, and tolerate being apart — because she''s confident you''ll still be there.

A baby who is held less, and whose bids for closeness are frequently unmet, doesn''t become more independent. She becomes more anxious and more clingy — because the tank is never full.

Holding Adelina is not indulgence. It is investment.', 'attachment, holding', 1, 0);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('raising_adelina', 'Scientists who study children who overcome tough circumstances — poverty, illness, loss — looked for the one factor that, above everything else, predicted whether a child would still turn out okay. What did they find?', '["A) Natural intelligence or a special talent","B) Getting into a good school early","C) Having at least one adult in their life who was consistently warm, present, and responsive to them","D) Having a strong group of friends"]', 'C) Having at least one adult in their life who was consistently warm, present, and responsive to them', 'multiple_choice', 'This finding — replicated across decades of resilience research — is one of the most hopeful things science has ever shown about children. It doesn''t take a perfect home, a perfect parent, or a perfect life. What it takes is *one person* who shows up reliably and loves that child in a way the child can feel.

That person doesn''t have to be a parent. It can be a grandparent. A grandmother. A grandfather.

You.

Every time Adelina is with you — and you look at her like she matters, respond when she reaches for you, stay calm when she''s upset, make her laugh — you are being that person for her. The research is clear: your presence in her life isn''t extra. It is foundational.', 'attachment, development, soothing', 1, 0);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('raising_adelina', 'Last one — and this one has no right or wrong answer.

Finish this sentence honestly:

''When Adelina is a teenager and something goes wrong in her life, I hope she feels _______ coming to me.''', '[]', 'Open response — any answer is welcome', 'free_form', 'Whatever word you chose — safe, comfortable, easy, unafraid — that feeling doesn''t appear out of nowhere at 16. It gets built right now, in moments like the ones this game has been about.

Research on grandparent relationships with teenagers is consistent: the adolescents who confide in their grandparents, who come to them when things go wrong, who trust them with their real lives — those relationships were built in the early years. Through ten thousand small moments of being responded to, seen, and not judged.

Connection-based relationships become the ones teenagers actually show up to.

You already love Adelina more than she will ever fully understand. Now you have the science behind how to make sure she always feels it.', 'attachment, development', 1, 0);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('raising_adelina', 'Scientists scanned the brains of different family members looking at photos of a baby in their family. Who showed the strongest emotional reaction?', '["A) Mother","B) Father","C) Grandfather","D) Uncle","E) Grandmother"]', 'E) Grandmother', 'multiple_choice', 'In a 2021 study led by anthropologist James Rilling at Emory University, grandmothers who looked at photos of their grandchildren showed the strongest activation in the parts of the brain associated with emotional empathy — the regions that light up when you feel what someone else is feeling, not just when you recognize or think about them. They outscored everyone — including mom and dad.

Interestingly, when the same grandmothers looked at photos of their own adult children, the response was different — more cognitive, less visceral. The effect was specific to grandchildren. The researchers believe this may be an evolutionary adaptation: grandmothers are neurologically primed to be emotionally in sync with their grandchildren in a unique and powerful way.', 'attachment, development', 1, 0);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('raising_adelina', 'When sung to versus spoken to, babies stayed calm _______ as long.', '["A) About the same amount of time","B) Nearly twice as long","C) About 20% longer","D) Depending on the song"]', 'B) Nearly twice as long', 'multiple_choice', 'Researcher Sandra Trehub at the University of Toronto spent decades studying how babies respond to music versus speech. Babies stayed calm and content nearly twice as long when sung to versus spoken to, even when the singer was completely untrained and the song was simple or made up.

What matters isn''t the quality of your voice or whether you know all the words. It''s the melody and rhythm — the rise and fall of the notes, the predictable pattern, the steady tempo. Babies'' brains are specifically tuned to process musical patterns, and that processing is calming in a way that regular speech isn''t.

So the next time you''re with Adelina and she''s fussy — try humming. Try an old song from your childhood, even if you only remember half the words.', 'singing, soothing, talking', 1, 0);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('raising_adelina', 'True or False: Playing classical music to babies has been proven by research to make them more intelligent.', '["True","False"]', 'False — the ''Mozart Effect'' was based on a misunderstood study and has never been replicated in babies', 'true_false', 'The ''Mozart Effect'' became one of the most successful myths in parenting history — it even prompted the state of Georgia to propose giving classical music CDs to every newborn. But the original 1993 study it was based on? It was conducted on college students, lasted 15 minutes, measured only one specific spatial reasoning task, and was never replicated.

Decades of follow-up research on infants found no lasting effect on intelligence from passive music exposure.

What does measurably support brain development in babies? Responsive back-and-forth conversation. Eye contact. Singing (actively, not just playing recordings). Being responded to when they cry. Narrating their surroundings to them.', 'playing, singing', 1, 0);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('raising_adelina', 'Studies show that babies whose caregivers spoke to them in a specific way had measurably larger vocabularies by age 2.

Fill in the blank: Babies whose caregivers used more ''________'' had significantly larger vocabularies at age 2 than babies who were spoken to in a normal adult tone of voice.', '["A) Complex vocabulary","B) Parentese (aka baby voice)","C) Bilingual input","D) Narration"]', 'B) Parentese (aka baby voice)', 'multiple_choice', 'You know that voice — the slightly silly, high-pitched, stretched-out, singsong way people instinctively talk to babies? Researchers call it ''parentese,'' and it turns out it isn''t silly at all.

A 2020 study published in the Proceedings of the National Academy of Sciences found that babies whose parents and caregivers used more parentese had measurably larger vocabularies at age 2 compared to babies spoken to in normal adult tones.

Why does it work? The exaggerated melody, slower pace, and clear vowel sounds are actually easier for a developing brain to process and learn from. Babies'' brains are specifically tuned to pick up on that speech pattern — it''s almost like it''s been highlighted for them.', 'talking, development', 1, 0);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('raising_adelina', 'Select all that apply: When you play peek-a-boo with Adelina, what is she learning?', '["A) Object permanence","B) That you will come back","C) Socialization","D) How to handle surprises","E) How to play jokes"]', 'A, B, C, and D are all true', 'select_all', 'Every single one of A through D is happening simultaneously every time you play peek-a-boo. E is the only false one.

On A — object permanence: Before about 8 months, babies genuinely believe that when something disappears from view, it simply ceases to exist. When you hide your face and reappear, you''re giving her brain direct evidence that the world is stable and permanent — that things continue to be real even when she can''t see them. Developmental psychologist Jean Piaget identified this as one of the foundational cognitive achievements of infancy.

On B — you come back: The emotional version of that same lesson is even more important. When you disappear and reappear, you''re teaching Adelina: the people I love go away sometimes, AND they come back. That knowledge — built through hundreds of peek-a-boo games — is part of what lets her eventually tolerate separation without panic.

On C — social laughter: Research shows that babies laugh earliest and most readily in response to people, not to toys or tickling. Mutual laughter between a caregiver and baby is one of the strongest early predictors of social competence. When Adelina laughs at your peek-a-boo, she isn''t just reacting to the motion. She is responding to you — and that distinction matters enormously for her social development.

On D — nervous system training: The tiny surge of suspense (''where did she go?'') followed by relief and delight (''there she is!'') is actually a micro-dose of stress followed by recovery — with a trusted person guiding the whole thing. Done lovingly and repeatedly, this is how babies learn that surprise is survivable and that the world after a scare can be joyful again.', 'development, playing', 1, 0);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('milestone_trivia', 'At almost 8 weeks old, Adelina flashed her very first smile. Who was the lucky audience?', '["A) Just Mommy","B) Just Daddy","C) Both Mommy and Daddy","D) The dog"]', 'C) Both Mommy and Daddy', 'multiple_choice', 'At just under 8 weeks old, Adelina smiled at both Mommy and Daddy — a social smile, which is different from the reflex smiles newborns do in their sleep. A social smile means she recognized faces she loves and responded to them. Big deal!', 'milestone, smiling', 1, 1);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('milestone_trivia', 'At 3 months old, Adelina gave her very first frown to who?', '["A) Pat","B) Tony","C) Grandma","D) Grandpa"]', 'B) Tony', 'multiple_choice', 'Tony was the recipient of Adelina''s debut frown at 3 months old. She was already forming opinions.', 'milestone, smiling', 1, 1);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('milestone_trivia', 'At 3 months, Adelina''s babbling suddenly went from zero to...', '["A) Quieter — she got more serious","B) Exponentially more — she couldn''t stop","C) Her first recognizable word","D) Mostly just squeaking"]', 'B) Exponentially more — she couldn''t stop', 'multiple_choice', 'Around 3 months, Adelina''s babbling exploded. Babies this age are discovering their voice and experimenting with sounds — it''s the very beginning of language development.', 'milestone, talking, babbling', 1, 1);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('milestone_trivia', 'At 3.5 months, Adelina made her first big physical move — literally. What did she do?', '["A) Rolled all the way over","B) Rolled to her side on her own","C) Pushed up on her arms","D) Sat up with no support"]', 'B) Rolled to her side on her own', 'multiple_choice', 'Not a full roll yet — but rolling to her side at 3.5 months is a real milestone. She was building the core strength and coordination that leads to full rolling.', 'milestone, rolling, tummy-time', 1, 1);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('milestone_trivia', 'At 3.5 months, Adelina hit a big nighttime milestone. What was it?', '["A) Slept a full 12 hours","B) Moved to her own room","C) No more nighttime feedings","D) Started using a pacifier"]', 'C) No more nighttime feedings', 'multiple_choice', 'Dropping nighttime feedings at 3.5 months is a huge deal — for Adelina and for the adults in the house. Her little body had grown enough to make it through the night without refueling.', 'milestone, sleeping', 1, 1);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('milestone_trivia', 'On Valentine''s Day, at exactly 4 months old, Adelina discovered a bold new use for her voice. What was it?', '["A) Laughing out loud","B) Blowing raspberries","C) Shrieking","D) Saying ''mama''"]', 'C) Shrieking', 'multiple_choice', 'Nothing says Happy Valentine''s Day like a baby discovering she can shriek. At 4 months, babies often find their upper vocal range and are delighted by the results. The adults are... also experiencing something.', 'milestone, talking, babbling', 1, 1);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('milestone_trivia', 'At 4 months, Adelina graduated to her crib. How was she already sleeping when she made the move?', '["A) Tightly swaddled","B) Arms out — no swaddle","C) In a sleep sack","D) On her tummy"]', 'B) Arms out — no swaddle', 'multiple_choice', 'Already arms out at 4 months! Babies who start breaking out of swaddles are usually ready to transition — and Adelina was ahead of the curve.', 'milestone, sleeping', 1, 1);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('milestone_trivia', 'At 4.5 months, Adelina figured out rolling — which direction did she master first?', '["A) Front to back","B) Back to front","C) Both at the same time","D) She skipped rolling and went straight to crawling"]', 'A) Front to back', 'multiple_choice', 'Front to back usually comes first — it''s a little easier because gravity helps. Adelina nailed it at 4.5 months, right on track.', 'milestone, rolling', 1, 1);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('milestone_trivia', 'Just four days after her first roll, what did Adelina do?', '["A) Refused to roll at all","B) Rolled both ways — multiple times","C) Rolled so much she fell off the mat","D) Added a spin move"]', 'B) Rolled both ways — multiple times', 'multiple_choice', 'Four days after mastering front-to-back, Adelina was rolling front to back AND back to front, multiple times in a row. Once babies get rolling, they go all in.', 'milestone, rolling', 1, 1);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('milestone_trivia', 'At nearly 5 months, Adelina hit two milestones in one day. What were they?', '["A) First laugh + first tooth","B) First time sleeping on her tummy + started sleep training","C) First solid food + first clap","D) First word + first high five"]', 'B) First time sleeping on her tummy + started sleep training', 'multiple_choice', 'A big day: Adelina slept on her stomach for the first time, and the family started fuss-it-out sleep training. Once babies can roll both ways, tummy sleeping is considered safe — because they can reposition themselves.', 'milestone, rolling, tummy-time', 1, 1);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('milestone_trivia', 'At 5 months old, Adelina made an exciting discovery about her own body. What did she find?', '["A) Her reflection in the mirror","B) Her belly button","C) Her toes — and she could grab them","D) Her own name"]', 'C) Her toes — and she could grab them', 'multiple_choice', 'Grabbing toes at 5 months is a classic baby milestone — it means her core strength and flexibility have developed enough to fold herself in half. Also, toes are fascinating. Frankly, we get it.', 'milestone, playing', 1, 1);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('milestone_trivia', 'By what age should Adelina be able to hold her head upright when held in a sitting position?', '["A) By 3 months","B) By 6 months","C) By 9 months","D) By 12 months"]', 'A) By 3 months', 'multiple_choice', '', 'milestone, sitting, tummy-time', 1, 0);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('milestone_trivia', 'By 6 months, Adelina should be able to _____.', '["A) Pull herself to standing","B) Sit independently without support","C) Roll from her tummy to her back","D) Crawl on hands and knees"]', 'C) Roll from her tummy to her back', 'multiple_choice', '', 'milestone, rolling, tummy-time', 1, 0);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('milestone_trivia', 'True or False: By 9 months, Adelina should be able to sit independently and play with toys.', '["True","False"]', 'True', 'true_false', '', 'milestone, sitting, playing', 1, 0);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('milestone_trivia', 'By what age should Adelina start babbling with consonant sounds like ''da, da''?', '["A) By 3 months","B) By 6 months","C) By 9 months","D) By 12 months"]', 'B) By 6 months', 'multiple_choice', '', 'milestone, talking, babbling', 1, 0);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('milestone_trivia', 'By 3 months, Adelina should be able to _____.', '["A) Babble with consonant sounds","B) Coo, smile, and turn her head toward your voice","C) Respond to her own name","D) Use gestures like raising her arms to be picked up"]', 'B) Coo, smile, and turn her head toward your voice', 'multiple_choice', '', 'milestone, smiling, talking', 1, 0);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('milestone_trivia', 'Which comes first?', '["A) Bouncing on her legs when held standing","B) Cruising along furniture"]', 'A) Bouncing on her legs when held standing', 'multiple_choice', '', 'milestone, standing, walking', 1, 0);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('milestone_trivia', 'By what age should Adelina be able to stand with support and start taking side steps along furniture?', '["A) By 3 months","B) By 6 months","C) By 9 months","D) By 12 months"]', 'C) By 9 months', 'multiple_choice', '', 'milestone, standing, walking', 1, 0);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('milestone_trivia', 'True or False: By 12 months, Adelina may be able to walk independently.', '["True","False"]', 'True — though the full range is 10–15 months', 'true_false', '', 'milestone, walking, standing', 1, 0);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('milestone_trivia', 'By 9 months, Adelina should be able to _____.', '["A) Say a few real words","B) Coo and make different cries for hunger vs. pain","C) Understand instructions like ''come here''","D) Shake her head ''no'' and raise her arms to be picked up"]', 'D) Shake her head ''no'' and raise her arms to be picked up', 'multiple_choice', '', 'milestone, talking, development', 1, 0);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('milestone_trivia', 'By what age should Adelina be able to lift her head and chest off the ground and reach for a toy?', '["A) By 3 months","B) By 6 months","C) By 9 months","D) By 12 months"]', 'B) By 6 months', 'multiple_choice', '', 'milestone, tummy-time, playing', 1, 0);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('milestone_trivia', 'Which comes first?', '["A) Responding to her own name","B) Understanding ''come to mummy''"]', 'A) Responding to her own name', 'multiple_choice', '', 'milestone, talking, development', 1, 0);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('milestone_trivia', 'True or False: By 3 months, Adelina should already have different cries for pain, hunger, and tiredness.', '["True","False"]', 'True', 'true_false', '', 'milestone, crying, feeding', 1, 0);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('milestone_trivia', 'By 12 months, Adelina should be able to _____.', '["A) Babble with varied syllables like ''bababba''","B) Take turns vocalizing back and forth with you","C) Follow a simple instruction like ''come here''","D) React to sudden loud noises"]', 'C) Follow a simple instruction like ''come here''', 'multiple_choice', '', 'milestone, talking, development', 1, 0);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('milestone_trivia', 'By what age should Adelina be able to get herself from lying down into a sitting position on her own?', '["A) By 3 months","B) By 6 months","C) By 9 months","D) By 12 months"]', 'C) By 9 months', 'multiple_choice', '', 'milestone, sitting', 1, 0);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('milestone_trivia', 'By 6 months, Adelina should be able to _____.', '["A) Point at things she wants","B) Take turns ''talking'' back and forth with you","C) Understand her own name","D) Use gestures to communicate"]', 'B) Take turns ''talking'' back and forth with you', 'multiple_choice', '', 'milestone, talking, babbling', 1, 0);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('milestone_trivia', 'Which comes first?', '["A) Passing toys between hands","B) Reaching and batting at toys"]', 'B) Reaching and batting at toys', 'multiple_choice', '', 'milestone, playing', 1, 0);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('milestone_trivia', 'By what age should Adelina be able to pull herself up to standing and cruise along furniture?', '["A) By 3 months","B) By 6 months","C) By 9 months","D) By 12 months"]', 'D) By 12 months', 'multiple_choice', '', 'milestone, standing, walking', 1, 0);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('milestone_trivia', 'True or False: By 9 months, Adelina should be able to look at a familiar object when you name it.', '["True","False"]', 'True', 'true_false', '', 'milestone, talking, development', 1, 0);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('milestone_trivia', 'By 3 months, Adelina should be able to _____.', '["A) Lift her head 45–90 degrees when lying on her tummy","B) Roll from tummy to back","C) Sit with hands for support","D) Bounce on her legs when held standing"]', 'A) Lift her head 45–90 degrees when lying on her tummy', 'multiple_choice', '', 'milestone, tummy-time', 1, 0);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('milestone_trivia', 'By what age should Adelina be able to pick up small objects using just her thumb and index finger?', '["A) By 3 months","B) By 6 months","C) By 9 months","D) By 12 months"]', 'D) By 12 months', 'multiple_choice', '', 'milestone, pincer-grip, playing', 1, 0);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('milestone_trivia', 'Which comes first?', '["A) Babbling with repeated syllables like ''bababba''","B) Saying a few real words"]', 'A) Babbling with repeated syllables like ''bababba''', 'multiple_choice', '', 'milestone, talking, babbling', 1, 0);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('milestone_trivia', 'True or False: By 6 months, Adelina should be able to sit completely independently without any support.', '["True","False"]', 'False — sitting independently comes by 9 months. At 6 months she uses her hands for support.', 'true_false', '', 'milestone, sitting', 1, 0);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('milestone_trivia', 'By what age should Adelina be able to point with her index finger?', '["A) By 3 months","B) By 6 months","C) By 9 months","D) By 12 months"]', 'C) By 9 months', 'multiple_choice', '', 'milestone, talking, development', 1, 0);
INSERT INTO trivia_questions (category, question, options_json, answer, answer_type, follow_up_context, tags, active, is_adelina_specific) VALUES ('milestone_trivia', 'By 12 months, Adelina should be able to _____.', '["A) Commando crawl","B) Stand briefly with furniture support","C) Walk only when both hands are held","D) Move freely between lying, sitting, and standing on her own"]', 'D) Move freely between lying, sitting, and standing on her own', 'multiple_choice', '', 'milestone, sitting, standing, walking', 1, 0);